Arreglar errores de concordancia y más
DiscordSafe/i18n pull request #4
Opened 2022-07-14 12:10 UTC by aidakhome

Hola, he arreglado algunos errores de concordancia, mayormente en casos en los que se trataba en una sola cadena de usted y luego no, además de algunos errores puntuales (le país xd) y alguna tilde suelta.

Aparte, en algunos mensajes de error el bot responde de esta manera:
**Error**, Ejemplo... por lo que he cambiado todos o la mayor parte (alguno me habré dejado) para que sea correcto.

Gracias por vuestro tiempo :)

2022-07-14 12:26 UTC, Vicente015 requested changes
Gracias por tu contribución, todo bien exceptuando algunos detalles para mejorar la consistencia :)

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
> +      "embedDescription": "Esta es la configuración actual de los filtros\n• Use `/filter setup` para activar o desactivar filtros.\n• Usa `/filter config` para personalizar la configuración.",
```suggestion
      "embedDescription": "Esta es la configuración actual de los filtros\n• Use `/filter setup` para activar o desactivar filtros.\n• Use `/filter config` para personalizar la configuración.",
```

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
> +    "noMismo": "**Error**, no te puedes banear a ti mismo.",
```suggestion
    "noMismo": "**Error**, no se puede banear a usted mismo.",
```

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
> +    "noCase": "**Error**, no se ha encontrado el caso, compruebe que la ID del caso sea correcto.",
```suggestion
    "noCase": "**Error**, no se ha encontrado el caso, compruebe que el ID del caso sea correcto.",
```

ID se refiere a identificador, es masculino

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
>      "errorArgs": "**Error**, debe mencionar, indicar la ID o el nombre de un usuario.",
```suggestion
    "errorArgs": "**Error**, debe mencionar, indicar el ID o el nombre de un usuario.",
```

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
> +    "noVálido": "**Error**, la ID de usuario no es válida."
```suggestion
    "noVálido": "**Error**, el ID de usuario no es válida."
```

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
> +    "errorAutor": "**Error**, no se puedes ensordecer a ti mismo.",
```suggestion
    "errorAutor": "**Error**, no se puede ensordecer a usted mismo.",
```

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
> +    "errorMención": "**Error: falta mencionar al usuario.\nEscríbalo como: `d.unmute @Usuario/ID Usuario`",
```suggestion
    "errorMención": "**Error**, falta mencionar al usuario.\nEscríbalo como: `d.unmute @Usuario/ID Usuario`",
```

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
> +    "errorAutor": "**Error**, no se puedes dar warn a usted mismo.",
```suggestion
    "errorAutor": "**Error**, no se puede dar warn a usted mismo.",
```

2022-07-14 12:26 UTC, Vicente015 commented on bot/es-ES/commands.json
> +    "desc": "Elija el orden en el que quieras que se muestren las advertencias",
```suggestion
    "desc": "Elija el orden en el que quiera que se muestren las advertencias",
```

2022-07-14 18:46 UTC, aidakhome commented
cuando mergean broma

2022-07-15 11:39 UTC, Vicente015 requested changes
inconsistencias por todos lados 😔 mete estos cambios y ya apruebo

2022-07-15 11:39 UTC, Vicente015 commented on bot/es-ES/commands.json
> +      "done": "Se ha establecido el límite de **{{limit}} {{action}}** a **1 minuto**."
Aquí es mejor "en" ya que hace referencia a la cantidad de tiempo y no es lo que se configura
![imagen](https://user-images.githubusercontent.com/33096355/179215436-0682d10d-7905-438e-900b-e8efa2bf2b79.png)


```suggestion
      "done": "Se ha establecido el límite de **{{limit}} {{action}}** en **1 minuto**."
```

2022-07-15 11:39 UTC, Vicente015 commented on bot/es-ES/commands.json
> +      "limits": "**+{{limit}} {{action}}** a **1 minuto**."
Mismo motivo que antes

```suggestion
      "limits": "**+{{limit}} {{action}}** en **1 minuto**."
```

2022-07-15 11:39 UTC, Vicente015 commented on bot/es-ES/commands.json
>      "reason_reason": "Has sido baneado en **{{guild}}** por: **{{reason}}**.",
```suggestion
    "reason_reason": "Ha sido baneado en **{{guild}}** por: **{{reason}}**.",
```

2022-07-15 11:39 UTC, Vicente015 commented on bot/es-ES/commands.json
>      "embedField4": "Bloquea la palabra que quieras con `/blockword word`.",
```suggestion
    "embedField4": "Bloquee la palabra que quiera con `/blockword word`.",
```

2022-07-15 11:39 UTC, Vicente015 commented on bot/es-ES/commands.json
> +    "errorAutor": "**Error**, No se puede ensordecer a usted mismo.",
```suggestion
    "errorAutor": "**Error**, no se puede ensordecer a usted mismo.",
```

2022-07-15 12:26 UTC, Vicente015 approved these changes
nice ;)

2022-07-15 12:26 UTC, merged

2022-07-15 12:29 UTC, aidakhome commented
Gracias :)